Pearson-Advance/frontend-app-institution-portal

- src/features/Instructors/InstructorsFilters/_test_/index.test.jsx
- src/features/Instructors/InstructorsFilters/index.jsx
- src/features/Instructors/InstructorsPage/index.jsx
- src/features/Instructors/InstructorsTable/index.jsx
- src/features/Instructors/data/api.js
https://agile-jira.pearson.com/browse/PADV-706
Add filters to instructors page
-  Add instructors filter component
- Adjust the service for filters
- Add tests
- Clone the Institution Portal MFE
- Run npm install.
- Run npm run start
- Go to http://localhost:1980/instructors
> PADV-706  Add filters to instructors table

- src/features/Instructors/AddInstructors/_test_/index.test.jsx
- src/features/Instructors/AddInstructors/index.jsx
- src/features/Instructors/data/_test_/api.test.js
- src/features/Instructors/data/api.js
https://agile-jira.pearson.com/browse/PADV-726
Call service add instructors 
Add service to modify access for instructor
Handle error when user does not exist
Add default value for select ccx for bug component
Add tests
Go to http://localhost:1980/instructors
> PADV-726 call service for add instructor

- src/features/Common/data/_test_/api.test.js
- src/features/Common/data/api.js
- src/features/Dashboard/DashboardPage/_test_/index.test.jsx
- src/features/Dashboard/DashboardPage/index.jsx
- src/features/Dashboard/DashboardPage/index.scss
- src/features/Dashboard/data/_test_/redux.test.jsx
- src/features/Dashboard/data/index.js
- src/features/Dashboard/data/slice.js
- src/features/Dashboard/data/thunks.js
- src/features/Licenses/LicensesTable/_test_/columns.test.jsx
- src/features/Licenses/LicensesTable/_test_/index.test.jsx
- src/features/Licenses/LicensesTable/columns.jsx
- src/features/Licenses/LicensesTable/index.jsx
- src/store.js
https://agile-jira.pearson.com/browse/PADV-894
Add license table in home page
Add license table component
Add data to store redux
Update tests
> PADV-894 Add license table in home page

- jsconfig.json
- src/features/Dashboard/DashboardPage/index.jsx
- src/features/Dashboard/DashboardPage/index.scss
- src/features/Licenses/LicensesPage/_test_/index.test.jsx
- src/features/Licenses/LicensesPage/index.jsx
- src/features/Licenses/LicensesTable/index.jsx
- src/features/Licenses/data/_test_/redux.test.jsx
- src/features/Licenses/data/index.js
- src/features/Licenses/data/slice.js
- src/features/Licenses/data/thunks.js
- src/features/Main/Sidebar/_test_/index.test.jsx
- src/features/Main/Sidebar/index.jsx
- src/features/Main/data/_test_/redux.test.js
- src/features/Main/data/slice.js
- src/features/Main/index.jsx
- src/store.js
https://agile-jira.pearson.com/browse/PADV-949
Add license table and licenses page
Add licenses page component
Add licenses in navbar
Add data to store redux
Move active tab to store 
Update tests
Go to http://localhost:1980/licenses
> PADV-949 Add licenses page

- src/features/Students/StudentsTable/_test_/columns.test.jsx
- src/features/Students/StudentsTable/_test_/index.test.jsx
- src/features/Students/StudentsTable/columns.jsx
https://agile-jira.pearson.com/browse/PADV-927
Update students table
Remove fields iin table according to wireframe
Add email field in table
Update tests
Go to http://localhost:1980/students
> PADV-927 feat: update students table

- .eslintignore
- .eslintrc.js
- package-lock.json
- package.json
- src/assets/colors.scss
- src/features/Common/data/_test_/api.test.js
- src/features/Common/data/api.js
- src/features/Dashboard/DashboardPage/index.jsx
- src/features/Dashboard/DashboardPage/index.scss
- src/features/Dashboard/InstructorAssignSection/ClassCard.jsx
- src/features/Dashboard/InstructorAssignSection/_test_/index.test.jsx
- src/features/Dashboard/InstructorAssignSection/index.jsx
- src/features/Dashboard/InstructorAssignSection/index.scss
- src/features/Dashboard/data/_test_/redux.test.jsx
- src/features/Dashboard/data/index.js
- src/features/Dashboard/data/slice.js
- src/features/Dashboard/data/thunks.js
- src/features/Instructors/InstructorsTable/columns.jsx
- src/features/Students/data/_test_/api.test.js
- src/features/Students/data/_test_/redux.test.js
- src/features/Students/data/api.js
- src/features/Students/data/thunks.js
- src/test-utils.js
- src/test-utils.jsx
https://agile-jira.pearson.com/browse/PADV-961
Add instructor assignment section
Add instructor assignment section
Move getClassesByInstitution to common folder
Replace moment for date-fns required for the calendar component
Update tests
Define renderWithProviders for redux test to avoid import of provider in every test
> PADV-961 feat: Add instructor assignment section

- src/features/Common/data/_test_/api.test.js
- src/features/Common/data/api.js
- src/features/Courses/CoursesFilters/index.jsx
- src/features/Courses/CoursesPage/_test_/index.test.jsx
- src/features/Courses/CoursesPage/index.jsx
- src/features/Dashboard/DashboardPage/index.jsx
- src/features/Dashboard/InstructorAssignSection/ClassCard.jsx
- src/features/Dashboard/InstructorAssignSection/index.jsx
- src/features/Dashboard/data/_test_/redux.test.jsx
- src/features/Instructors/InstructorsFilters/index.jsx
- src/features/Instructors/InstructorsPage/_test_/index.test.jsx
- src/features/Instructors/InstructorsPage/index.jsx
- src/features/Instructors/data/_test_/api.test.js
- src/features/Instructors/data/api.js
- src/features/Instructors/data/thunks.js
- src/features/Licenses/LicensesPage/_test_/index.test.jsx
- src/features/Licenses/LicensesPage/index.jsx
- src/features/Licenses/data/_test_/redux.test.jsx
- src/features/Licenses/data/thunks.js
- src/features/Main/data/slice.js
- src/features/Main/index.jsx
- src/features/Main/index.scss
- src/features/Students/StudentsFilters/index.jsx
- src/features/Students/StudentsMetrics/index.jsx
- src/features/Students/StudentsPage/_test_/index.test.jsx
- src/features/Students/StudentsPage/index.jsx
- src/features/Students/data/_test_/api.test.js
- src/features/Students/data/api.js
- src/features/Students/data/thunks.js
https://agile-jira.pearson.com/browse/PADV-731
Add institution selector
Add institution selector
Update files where institution id is necessary
Update services missing institution id
Update test
> PADV-731  add institution selector

- src/features/Dashboard/InstructorAssignSection/ClassCard.jsx
- src/features/Dashboard/InstructorAssignSection/index.jsx
- src/features/Dashboard/InstructorAssignSection/index.scss
- src/features/Instructors/AssignInstructors/AssignTable.jsx
- src/features/Instructors/AssignInstructors/ControlledSelect.jsx
- src/features/Instructors/AssignInstructors/_test_/index.test.jsx
- src/features/Instructors/AssignInstructors/columns.jsx
- src/features/Instructors/AssignInstructors/index.jsx
- src/features/Instructors/AssignInstructors/index.scss
- src/features/Instructors/InstructorsFilters/index.jsx
- src/features/Instructors/InstructorsTable/columns.jsx
- src/features/Instructors/data/_test_/redux.test.js
- src/features/Instructors/data/index.js
- src/features/Instructors/data/slice.js
- src/features/Instructors/data/thunks.js
- src/features/constants.js
https://agile-jira.pearson.com/browse/PADV-966
Add assign instructors modal from home page
Add assign instructors modal
Call service for every instructor
Adjust styles according to wireframe
Add tests
> PADV-966 feat: Add assign instructors modal

- src/features/Instructors/AddInstructors/_test_/index.test.jsx
- src/features/Instructors/AddInstructors/index.jsx
- src/features/Instructors/InstructorsPage/_test_/index.test.jsx
- src/features/Instructors/InstructorsPage/index.jsx
- src/features/Instructors/data/_test_/api.test.js
- src/features/Instructors/data/_test_/redux.test.js
- src/features/Instructors/data/api.js
- src/features/Instructors/data/index.js
- src/features/Instructors/data/slice.js
- src/features/Instructors/data/thunks.js
https://agile-jira.pearson.com/browse/PADV-973
Add instructor modal
Update add instructor modal
Remove classes fetch used in the past component
Update tests
Go to http://localhost:1980/instructors
> PADV-973 feat: add instructor modal

- src/features/Instructors/AssignInstructors/index.jsx
- src/features/Instructors/data/_test_/redux.test.js
- src/features/Instructors/data/slice.js
- src/features/Instructors/data/thunks.js
https://agile-jira.pearson.com/browse/PADV-1068
Fix instructors list select in assign modal
Reset instructors list selected after close modal and after call assign service
Disabled assign button if there are not instructors selected
Update tests
> PADV-1068 fix: assign instructors list

- src/features/Instructors/InstructorsDetailPage/index.jsx
- src/features/Instructors/InstructorsDetailPage/index.scss
This PR fixes the weird shadow that appears in the most of the tables, this visual error is more clear if the table is empty.
- removed extra padding for tables.
- added bootstrap margin class for tab.
> fix: top shadow in tables

- src/features/Classes/Class/ClassPage/columns.jsx
- src/features/Instructors/InstructorsTable/columns.jsx
- src/features/Students/StudentsTable/columns.jsx
This PR adds the [mailto](https://css-tricks.com/snippets/html/mailto-links/) in email columns.
This PR resolves [PADV-1112](https://agile-jira.pearson.com/browse/PADV-1112)
- Added mailto in columns.
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Finally, go to:
- http://localhost:1980/instructors
- http://localhost:1980/students
- http://localhost:1980/courses/:courseId/:classId
and see the result.
> feat: mailto in emails

- src/features/Main/ActiveTabUpdater/index.jsx
- src/features/Main/__test__/index.test.jsx
- src/features/Main/index.jsx
This PR fixes the error in the selection on the sidebar.
This PR resolves [PADV-1104](https://agile-jira.pearson.com/browse/PADV-1104)
- Fixed error when you reload the page or use a link to go into institution portal.
- Refactor in routes.
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
- Pick any section [home, instructors...], reload the page the sidebar should show the section selected.
- Follow the previous step, pick the url and open it into other tab, the sidebar should show the current selection.
> fix: Sidebar router selection

- package-lock.json
- package.json
- src/assets/global.scss
- src/features/Main/Sidebar/index.jsx
- src/features/Main/index.jsx
- src/features/Main/index.scss
In this pr is updated the sidebar, now is being using the sidebar from https://www.npmjs.com/package/react-paragon-topaz
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Finally, go to:
- http://localhost:1980/
You should be able to navigate to all sections using the new sidebar.
> refactor: import sidebar from library

- src/assets/global.scss
- src/features/Courses/CourseDetailTable/__test__/columns.test.jsx
- src/features/Courses/CourseDetailTable/columns.jsx
In this PR is added a drop-down for course detail table.
https://agile-jira.pearson.com/browse/PADV-1239
- Removed add insctructor button.
- Labels in some test cases.
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Then go to "class details" and interact with the new options.
> feat: dropdown option in course detail table

- src/features/Courses/CoursesDetailPage/index.jsx
- https://agile-jira.pearson.com/browse/PADV-1412
This PR fix the problem related to enter into a course and then try to go into course details and can't access because the courseInfo is not in the Redux State.
> fix: obtain courseInfo in CoursesDetailsPage.

- package-lock.json
- package.json
https://agile-jira.pearson.com/browse/PADV-1369
In this PR is updated the library `react-paragon-topaz` to the version `1.8.0` which includes styles to add sticky effect on sidebar.
https://github.com/Pearson-Advance/react-paragon-topaz-library/assets/52179095/8fe91f4a-b1f8-4621-8e99-f456c79347d8
- Clone the repo
- Install the dependencies
- run `npm start`
- Check the result on browser ( this result is only visible if the content has scroll but you can fake it using the dev tools )
> feat: sticky sidebar

- src/features/Classes/EnrollStudent/__test__/index.test.jsx
- src/features/Classes/EnrollStudent/index.jsx
- src/features/Students/data/_test_/api.test.js
- src/features/Students/data/api.js
https://agile-jira.pearson.com/browse/PADV-1380
In this PR is handled the error when the user reach the limit of seats in inrollments.
- Clone the repo
- Install the dependencies
- run `npm start`
- Go to `/institution-portal/courses/courseId/classId` fill the seats enrolling people, when you reach the limit you should be able to see the error message..
> feat: error message on reach limit seats in enrollment feature

- src/features/Classes/EnrollStudent/index.jsx
- src/features/Courses/AddClass/index.jsx
- src/features/Courses/CourseDetailTable/columns.jsx
- src/features/Instructors/ManageInstructors/index.jsx
This PR addresses an issue with the toast component where messages, particularly class names, were being displayed in an encoded format. The update ensures that messages are now correctly decoded before being shown, preventing further occurrences of this issue.
> fix: decode message for toast component

- src/features/Dashboard/WeeklySchedule/__test__/index.test.jsx
- src/features/Dashboard/WeeklySchedule/index.jsx
https://agile-jira.pearson.com/browse/PADV-1441
In this PR is fixed the class title in class schedule, now is an item clickable.
- Make sure to have a class with the current start date
- Go to /dashboard, you should be able to see the class listed in class schedule and click in its title.
> fix: class title in class schedule should be clickable

- src/features/Main/Sidebar/index.jsx
At the moment to make db click on any section in the sidebar, the sidebar loses the selection we still in the section selected but the sidebar does not reflect that, this PR fix it.
https://github.com/user-attachments/assets/086d945e-f2dd-4146-a3b2-ab2b2d8bec83
> fix: sidebar selection on db click

- src/features/Licenses/LicensesDetailPage/__test__/index.test.jsx
- src/features/Licenses/LicensesDetailPage/index.jsx
- src/features/Licenses/LicensesDetailPage/index.scss
https://agile-jira.pearson.com/browse/PADV-1494
In order to be consistence with values for licenses, we decided to calculate remaining value correctly.
- Clone the Institution Portal MFE
- Run npm install
- Run npm run start
- Go to http://localhost:1980/institution-portal/
- Go to license view and verify if remaining value is the same in license details
> PADV-1494 (BUG) - Calculate remaining value in license details

- src/features/Courses/CoursesFilters/index.jsx
This PR resolves [PADV-1882](https://agile-jira.pearson.com/browse/PADV-1882) now the filter shows the search made
- Updated `CourseFilters` to show the search maded.
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Finally, go to courses/ and test the results.
> feat: display search on course filter

- src/features/Courses/CoursesFilters/index.jsx
- src/features/Courses/data/slice.js
This PR adds a toggle button to filter the courses.
This PR resolves [PADV-1793](https://agile-jira.pearson.com/browse/PADV-1793)
> [!WARNING]  
> You must have the changes of the PR https://github.com/Pearson-Advance/course_operations/pull/286 if the PR still unmerged in main branch do a checkout to test this locally 
- Added button to filter courses
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Finally, go to /courses and test the results.
> feat: switch button to get only my courses

- src/features/Instructors/InstructorsDetailPage/__test__/index.test.jsx
- src/features/Instructors/InstructorsDetailPage/index.jsx
- src/features/Instructors/data/__test__/api.test.js
- src/features/Instructors/data/api.js
- src/features/Instructors/data/index.js
- src/features/Instructors/data/slice.js
- src/features/Instructors/data/thunks.js
Is added `Profile` tab in instructor detail page.
This PR resolves [PADV-1637](https://agile-jira.pearson.com/browse/PADV-1637)
- Added `ProfileCard` from `react-paragon-topaz`
- Added instructor info in `InstructorDetailPage`
- Updated unit test
- Go to /instructors and select one
You should be able to see the instructor profile tab
> feat: instructor profile info

- src/features/Courses/CoursesFilters/__test__/index.test.jsx
- src/features/Courses/CoursesFilters/index.jsx
- src/features/Courses/data/slice.js
This PR updates the functionality of the toggle used to filter courses. Previously, when you visited _http://localhost:1980/institution-portal/courses_ and entered a search term to find a course, toggling the "Show my courses" option would leave the search term intact in the filter. This PR fixes that issue by clearing the input so that only your courses are displayed. Additionally, if you enable the toggle to show your courses and then perform a new search, the toggle automatically resets to its default state.
_This PR resolves [PADV-2058](https://agile-jira.pearson.com/browse/PADV-2058)_
- Renamed test folder, now uses double _
- Improved unit test.
- Removed state for redux, now is handled locally by the component.
- Renamed boolean variables for something more meaningful.
Open the …
> fix: course filters toggle

- src/features/Students/StudentsFilters/index.jsx
This PR updates the input type in **StudentsFilter**, changing it from `email` to `text` to enable **partial email searches**. Previously, searches required a full email match, but with this change, users can find students by entering only a part of their email.  
This improves usability when filtering students based on incomplete email information.  
This PR resolves [PADV-1907](https://agile-jira.pearson.com/browse/PADV-1907)  
- Changed input type from `email` to `text` in **StudentsFilter**  
- Enabled partial email searches  
_No visual changes_
1. Go to the **StudentsFilter** form.  
2. Enter a partial email in the search field.  
3. The table should display students matching the partial email input.  
4. You should be able to find a student without entering their full email …
> fix: change email input type to text in student filters

- src/features/Main/Header/index.jsx
This PR updates the **header** to display the user's **full name** instead of their username. If the user **does not have a full name configured**, the username will still be displayed as the default value.  
This PR resolves [PADV-2063](https://agile-jira.pearson.com/browse/PADV-2063)  
- Updated the header to display the **full name** instead of the username.  
- If the full name is not available, the username remains as the fallback.  
_No visual changes._  
1. Start the application.  
2. Check the **header** to confirm that the **user's full name** is displayed.  
3. If the user does not have a full name set, the username should still be displayed.
> feat: full username instead of username

- src/features/Instructors/InstructorsFilters/index.jsx
This PR updates the input type in **InstructorsFilters**, changing it from `email` to `text` to enable **partial email searches**. Previously, searches required a full email match, but with this change, users can find instructors by entering only a part of their email.  
This improves usability when filtering instructors based on incomplete email information.  
This PR is part of [PADV-1907](https://agile-jira.pearson.com/browse/PADV-1907)  
- Changed input type from `email` to `text` in **InstructorsFilters**  
- Enabled partial email searches  
_No visual changes_
1. Go to the **InstructorsFilters** form.  
2. Enter a partial email in the search field.  
3. The table should display instructors matching the partial email input.  
4. You should be able to find a instructor without …
> fix: change email input type to text in instructors filters

- src/features/Main/Header/index.jsx
This PR resolves [PADV-2063](https://agile-jira.pearson.com/browse/PADV-2063)  
- Fixed an issue where the header displayed `nofullname` when the authenticated user's `name` existed but contained that value.  
1. Use a test user whose `user.profile.name` field is set. The header should display that name.  
2. Use another test user with no value set for `user.profile.name` or with `"nofullname"`. The header should now display the `username` instead.  
3. Verify that removing the `user.profile.name` value also results in the `username` being displayed.
> fix: username when value is 'nofullname'

- src/features/Instructors/AddInstructors/__test__/index.test.jsx
- src/features/Instructors/AddInstructors/index.jsx
In this PR is added the toggle to grand enrollment permissions at the moment to create an instructor
This PR resolves [PADV-2136](https://agile-jira.pearson.com/browse/PADV-2136)
- Added toggle input in form to add a new instructor.
- Set in the site configurations the flag `SHOW_INSTRUCTOR_FEATURES` in `true`.
- Go to `/institution-portal/instructors` then add a new instructor, make sure to toggle the input in true.
> feat: add enrollment permission toggle to instructor form

- src/features/Instructors/InstructorsFilters/__test__/index.test.jsx
- src/features/Instructors/InstructorsFilters/index.jsx
This PR enhances the `InstructorsFilters` component by introducing a new toggle switch that filters instructors based on their active status. This switch is conditionally rendered when the `SHOW_INSTRUCTOR_FEATURES` flag is `enabled`. To improve performance and reduce unnecessary server load, a debounce mechanism has been implemented on the filters request. Unit tests have been updated to reflect all relevant component states, including additional test cases for the newly introduced filter.
[PADV-2348](https://agile-jira.pearson.com/browse/PADV-2348)
- Enable `SHOW_INSTRUCTOR_FEATURES` in the site config.
- Go to `/instructors`, use the filters
> feat: active status toggle filter in instructors filters

- src/features/Instructors/ManageInstructors/_test_/columns.test.jsx
- src/features/Instructors/ManageInstructors/columns.jsx
In this PR is added the instructor email column in assign instructor page.
https://agile-jira.pearson.com/browse/PADV-2224
_Before_
_After_
- Start services
- Go to assign instructors page
> feat: add email column to instructors table in assign instructors view

- src/features/Classes/data/_test_/thunks.test.js
- src/features/Classes/data/thunks.js
- https://pearson.atlassian.net/browse/PADV-2156
This update refines the “Classes Insights (Beta)” action in the Classes table so that the resulting link is smart:
- If the browser already carries a valid Superset session cookie: The user is sent straight to the “Classes” dashboard (zero extra hops).
- If the session is missing or expired: The link falls back to /login/?next= and lands on the dashboard after sign-in.
The deep link still arrives pre-filtered to the selected class (course_key = <classId>) and is only rendered when all three Superset-related environment variables are present.
- Set the site configurations
```
export SUPERSET_HOST=https://superset.local
export SUPERSET_DASHBOARD_SLUG=classes
export SUPERSET_CLASS_FILTER_ID=COURSE_KEY
```
- Re-build the MFE image and run tutor …
> PADV-2156 - auto-detect Superset session and skip /login redirect.

- src/features/Classes/ClassesTable/columns.jsx
- src/features/Courses/CourseDetailTable/columns.jsx
- src/features/Courses/CoursesDetailPage/index.jsx
This PR improves the instructor display functionality by showing instructor names instead of usernames in the class list.
- Modified the instructor mapping logic to match usernames with instructor data from Redux state.
_Before_
_After_
- Added a `find()` operation to match `instructorUsername` from the Redux state with the usernames in `row.values.instructors`
- Implemented safe navigation (`?.`) to handle cases where instructor data might not be found
- Preserved the original username as a fallback to ensure the UI remains functional even with missing data
- Go to `/classes` or `/courses/:courseId` to see the results
> feat: instructor full name instead of user name
