Pearson-Advance/frontend-app-institution-portal

src/features/Instructors/AddInstructors/_test_/index.test.jsx, src/features/Instructors/AddInstructors/index.jsx
Disable add instructor modal until get the new design in order to avoid bugs
Remove event button to open modal
Update test to not fail
=> feat: disable add instructor modal

package-lock.json, package.json, src/features/Dashboard/DashboardPage/index.jsx, src/features/Dashboard/DashboardPage/index.scss, src/features/Dashboard/InstructorAssignSection/_test_/index.test.jsx, src/features/Dashboard/InstructorAssignSection/index.jsx, src/features/Dashboard/WeeklySchedule/_test_/index.test.jsx, src/features/Dashboard/WeeklySchedule/index.jsx, src/features/Dashboard/WeeklySchedule/index.scss, src/features/Dashboard/data/_test_/redux.test.jsx, src/features/Dashboard/data/slice.js, src/features/Dashboard/data/thunks.js, src/index.scss
https://agile-jira.pearson.com/browse/PADV-893
Add weekly schedule UI section in home
Add weekly schedule section
Add component for library
Adjust styles according to wireframe
Update tests
=> PADV-893 feat: Add weekly schedule UI

src/features/Courses/CoursesTable/_test_/columns.test.jsx, src/features/Courses/CoursesTable/_test_/index.test.jsx, src/features/Courses/CoursesTable/columns.jsx
https://agile-jira.pearson.com/browse/PADV-975
Update courses table
Update courses table data
Update tests
Go to http://localhost:1980/courses
=> PADV-975 feat: update courses table

src/features/Instructors/InstructorsFilters/_test_/index.test.jsx, src/features/Instructors/InstructorsFilters/index.jsx, src/features/Students/StudentsFilters/_test_/index.test.jsx, src/features/Students/StudentsFilters/index.jsx
https://agile-jira.pearson.com/browse/PADV-971
https://agile-jira.pearson.com/browse/PADV-972
Update filters in student and instructor page
Update filters in student page
Update filters in instructor page
Update test
Student page:
Instructor Page:
Go to http://localhost:1980/students
Go to http://localhost:1980/instructor
=> PADV-971, PADV-972 feat: update filters in student  and instructor page

src/assets/colors.scss, src/assets/global.scss, src/features/Students/StudentsTable/_test_/columns.test.jsx, src/features/Students/StudentsTable/columns.jsx
https://agile-jira.pearson.com/browse/PADV-969
Update students table with start-end class date and progress bar
Show start-end class date and progress bar
Adjust styles according to wireframe
Update tests
Go to http://localhost:1980/students
=> PADV-969 feat: Update students table

src/features/Classes/ClassesFilters/__test__/index.test.jsx, src/features/Classes/ClassesFilters/index.jsx, src/features/Classes/ClassesPage/index.jsx, src/features/Classes/ClassesTable/index.jsx, src/features/Classes/data/_test_/redux.test.js, src/features/Classes/data/thunks.js, src/features/Common/data/_test_/api.test.js, src/features/Common/data/api.js, src/features/Courses/data/slice.js, src/features/Courses/data/thunks.js, src/features/Dashboard/data/_test_/redux.test.jsx, src/features/Instructors/data/slice.js, src/features/Instructors/data/thunks.js, src/features/Students/data/_test_/redux.test.js
This PR adds the `ClassFilters` component, allowing users to filter by courses and instructors. It integrates the selector from React Paragon and Topaz libraries for courses options and utilizes form control from Paragon for classes and instructors. This implementation aims to enhance user experience and simplify the filtering process.
This PR resolves [PADV-1046](https://agile-jira.pearson.com/browse/PADV-1046)
- Created the `ClassesFilters` component.
- The component is integrated in the view `src/features/Classes/ClassesPage/index.jsx`.
- Updated unit test.
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Finally, go to http://localhost:1980/classes and see the results.
=> feat: Filters in classes page

src/assets/global.scss, src/features/Classes/Class/ClassPage/__test__/columns.test.jsx, src/features/Classes/Class/ClassPage/__test__/index.test.jsx, src/features/Classes/Class/ClassPage/columns.jsx, src/features/Classes/Class/ClassPage/index.jsx, src/features/Courses/CourseDetailTable/__test__/columns.test.jsx, src/features/Courses/CourseDetailTable/columns.jsx, src/features/Courses/CoursesDetailPage/index.jsx, src/features/Main/Table/__test__/index.test.jsx, src/features/Main/Table/index.jsx, src/features/Main/index.jsx, src/features/Students/data/slice.js
This PR adds the detail page for a course.
This PR resolves [PADV-985](https://agile-jira.pearson.com/browse/PADV-985)
- Changed the importation order in `src/features/Main/index.jsx`
- Added new path in `src/features/Main/index.jsx`
- New general component Table `src/features/Main/Table/index.jsx`
- New view `src/features/Lessons/LessonDetailPage/index.jsx`
- New link to the new page in `/src/features/Courses/CourseDetailTable/columns.jsx`
- Refactor in `src/assets/global.scss` to make more simple the way in how implement the styles for progress bar
- Added `src/features/Lessons/.gitkeep`, it does not affect the project just make the folder structure more organized for vscode.
```Bash
```
```Bash
npm i
```
Start …
=> feat: Class detail page

src/assets/global.scss
This PR fixes the styles for progress bar in courses - courses detail.
=> fix: Styles for progress bar in courses

src/features/Classes/Class/ClassPage/__test__/index.test.jsx, src/features/Classes/Class/ClassPage/index.jsx, src/features/Classes/EnrollStudent/__test__/index.test.jsx, src/features/Classes/EnrollStudent/index.jsx, src/features/Classes/EnrollStudent/index.scss, src/features/Courses/CourseDetailTable/__test__/columns.test.jsx, src/features/Courses/CourseDetailTable/columns.jsx, src/features/Courses/CoursesDetailPage/index.jsx, src/features/Courses/CoursesDetailPage/index.scss
This PR adds the modal and button for enroll students.
This PR resolves [PADV-986](https://agile-jira.pearson.com/browse/PADV-986)
- Added enroll button in `src/features/Classes/Class/ClassPage/index.jsx`
- Added component for enroll modal student `src/features/Classes/EnrollStudent/index.jsx`
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Finally, go to http://localhost:1980/courses/:courseId/:classId and see the results.
=> feat: Student enrollment modal

src/features/Classes/Class/ClassPage/index.jsx
https://agile-jira.pearson.com/browse/PADV-12264
In this PR is fixed the selection in the sidebar when we're navigating in class detail page.
=> fix: sidebar selection on class detail page

src/features/Classes/Class/ClassPage/Actions.jsx, src/features/Classes/Class/ClassPage/__test__/index.test.jsx
Fix link to push in manage instructors button
Use history to link to manage instructors button
Go to courses -> class -> class detail
=> FIX PADV-1307  link to push

src/features/Classes/ClassesTable/columns.jsx
In this PR is added a new link in drop down menu in order to be redirected to the new manage instructor page.
https://agile-jira.pearson.com/browse/PADV-1308
- Removed assign button for instructor if the course does not have any instructor assigned.
- New link for manage instructors.
=> feat: redirect link to manage instructors in classes table

src/features/Courses/CourseDetailTable/__test__/columns.test.jsx, src/features/Courses/CoursesDetailPage/index.jsx, src/features/Courses/CoursesTable/columns.jsx, src/features/Licenses/LicenseDetailTable/columns.jsx
https://agile-jira.pearson.com/browse/PADV-1412
This PR fixes malformed url when you go to course details.
- Clone the Institution Portal MFE
- Run npm install
- Run npm run start
- Go to http://localhost:1980/institution-portal/courses
- Click in Course Details bottom
- Verify if the redirection is correct
=> PADV-1412 - Fix course details link

src/features/Courses/AddClass/index.jsx, src/features/Courses/data/thunks.js
In this PR is modified the behavior when a class is created, after a successful class creation the platform will redirect to the class details of the created class. 
This PR resolves [PADV-1796](https://agile-jira.pearson.com/browse/PADV-1796)
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Finally, create a new class, after a successful creation the platform should redirect you to the new class.
=> feat: redirection after a class creation

src/features/Classes/Class/ClassPage/Actions.jsx, src/features/Classes/Class/ClassPage/__test__/index.test.jsx, src/features/Classes/ClassesTable/columns.jsx, src/features/constants.js
This PR resolves [PADV-1815](https://agile-jira.pearson.com/browse/PADV-1815)
- New constant in constants file
- Refactor for button layout
- Added new options for dropdown
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Finally, go to class details and see the results.
=> feat: new actions button redistribution in class details

package-lock.json, package.json, src/features/Courses/data/_test_/redux.test.js, src/features/Courses/data/thunks.js
This PR resolves [PADV-1732](https://agile-jira.pearson.com/browse/PADV-1732) now the courses comes sorted alphabetically.
- Imported function to sort courses by name
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Finally, find all courses and check if they're sorted.
=> feat: sort for courses alphabetically

src/features/Classes/Class/ClassPage/Actions.jsx, src/features/Classes/InstructorCard/__test__/index.test.jsx, src/features/Classes/InstructorCard/index.jsx, src/features/Main/index.scss
This PR resolves [PADV-1814](https://agile-jira.pearson.com/browse/PADV-1814)
- Updated button redistribution in class details
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Finally, go to class details page and test the results.
=> refactor: manage instructors buttons in class page

src/features/Courses/CoursesFilters/index.jsx
This PR adds a flag to show or hide the button toggle for course filter 
- Added flag in coursefilters
```Bash
```
```Bash
npm i
```
Start project.
```Bash
npm start
```
Finally, go to /courses and test the results.
=> feat: site setting to control the toggle visibility in courses

package-lock.json, package.json
In this PR is updated the version of `react-paragon-topaz`
- Updated package version
=> feat: update version of react-paragon-topaz

package-lock.json, package.json
This PR updates the `react-paragon-topaz` library version to include multiple improvements and fixes related to event handling and display.  
- [Hide interaction buttons when the event is a class](https://github.com/Pearson-Advance/react-paragon-topaz-library/pull/55).  
- [Style fixes for events with long names to improve readability](https://github.com/Pearson-Advance/react-paragon-topaz-library/pull/56).  
- [Added a new field to display the event `description`](https://github.com/Pearson-Advance/react-paragon-topaz-library/pull/52).  
- [Introduced a recurrence field to properly handle recurring events](https://github.com/Pearson-Advance/react-paragon-topaz-library/pull/54).  
- Create events using the modal and verify that interaction buttons are hidden when the event is a class.  
- …
=> feat: update react-paragon-topaz version

public/index.html, src/features/Main/Header/__test__/index.test.jsx, src/features/Main/Header/index.jsx
In this PR is updated the header title
This PR resolves [PADV-1998](https://agile-jira.pearson.com/browse/PADV-1998)
- Updated header title and updated unit test.
- Start the project and go to http://localhost:1980/institution-portal/dashboard
=> feat: update header title

src/features/Main/Header/index.jsx
This PR is part of [PADV-2063](https://agile-jira.pearson.com/browse/PADV-2063) removes the hardcoded logic used to handle users without a full name, as it was fragile and subject to potential changes. Instead, it defaults to showing "nofullname" when no full name is available, relying on the backend to eventually update this behavior. If the user has a valid value, it displays the full name or "nofullname"; otherwise, it shows the username. Additionally, the variable responsible for displaying the name was refactored for better clarity.
- Removed hardcoded logic for handling users without a full name.
- Now defaults to showing `nofullname` if no full name is provided, relying on backend to handle this.
- Small refactor to the variable responsible for displaying the name for improved …
=> refactor: hardcoded fullname conditional in header

src/features/Main/UnauthorizedPage/__test__/index.test.jsx, src/features/Main/UnauthorizedPage/index.jsx, src/features/constants.js
This PR updates the message for unauthorized page.
Resolves [PADV-2295](https://agile-jira.pearson.com/browse/PADV-2295)
- Small refactor in `constants`.
- Updated message
- Start the services.
- Login with an user without any role ( admin, institution_admin )
=> feat: new message for unauthorized users

package-lock.json, src/features/Main/Sidebar/index.jsx
This PR adds help links into the side bar.
https://pearson.atlassian.net/browse/PADV-1160
No special configuration needed
=> feat: Help links in sidebar

src/features/Classes/ClassesPage/_test_/index.test.jsx, src/features/Classes/ClassesTable/_test_/columns.test.jsx, src/features/Classes/ClassesTable/_test_/index.test.jsx, src/features/Classes/ClassesTable/columns.jsx, src/features/Classes/EnrollStudent/index.jsx, src/features/Courses/CourseDetailTable/__test__/columns.test.jsx, src/features/Courses/CourseDetailTable/__test__/index.test.jsx, src/features/Courses/CourseDetailTable/columns.jsx, src/features/Courses/CoursesDetailPage/__test__/index.test.jsx
This pull request introduces a new item in the class enrollment dropdown, allowing users to enroll a student into a new class. It includes the necessary updates to related test files to ensure coverage of the new functionality.
navigate to:
* `/classes`
* `/courses/:classId`
=> Enroll Student functionality
